// DatingSite/client/src/app/app.component.ts
import { HttpClient } from '@angular/common/http';
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  title = 'client';
  users: any;

  constructor(private httpClient: HttpClient) {

  }
  ngOnInit(): void {
    this.getUsers();
  }

  getUsers() {
    this.httpClient.get("https://localhost:7061/api/users").subscribe(response => {
      this.users = response;
    }, error => {
      console.log(error);
    });
  }


}

<p> {{title}}</p>

// ActivityApp/client/src/App.tsx
import React, { useEffect, useState } from 'react';
import './App.css';
import axios from 'axios';
import { Header, List } from "semantic-ui-react";   

function App() {
    const [activities, setActivities] = useState([]);

    useEffect(() => {
        axios.get("https://localhost:5001/api/activities").then(response => {
            setActivities(response.data);
            console.log(response.data);
        })
    }, []);




    return (
        <div>
            <Header as='h2' icon='users' content='Activities' />
            <List>
                {activities.map((activity: any) => (
                    <List.Item key={activity.id}>
                        {activity.title}
                    </List.Item>
                ))}
            </List>
        </div>
    );
}

export default App;
